apps/seguimiento/urls.py
from django.urls import path

# Vistas
from .views import SeguimientoNew, ReceivedData, download_patient_list, PatientList

urlpatterns =[
    # Public
    path('', SeguimientoNew.as_view(), name='seguimiento_new'),
    path('datos_recibidos/', ReceivedData.as_view(), name='datos_recibidos'),
    # Dashboard
    path('listado_pacientes/', PatientList.as_view(), name='listado_pacientes'),
    path('descargar_listado_pacientes', download_patient_list, name='descargar_listado_pacientes'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('osepcontrol/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include(('apps.seguimiento.urls', 'seguimiento'), namespace='seguimiento'),),
    path('usuarios/', include(('apps.usuarios.urls', 'usuarios'), namespace='usuarios'),),
]

""" Si estan activas las herramientas de desarrollo agrego la ruta a debug. """
if settings.ACTIVAR_HERRAMIENTAS_DESARROLLO:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/seguimiento/models.py
from django.db import models

from apps.generales.models import ModeloBase


class Seguimiento(ModeloBase):
    SELECCIONAR = 'Seleccione una opción'
    NO_CONTACTADO = 'No fuí contactado nunca por el profesional encargado del seguimiento'
    NO_SEGUIDO = 'El profesional no realiza el seguimiento todos los días'
    CONFORME = 'Estoy conforme con el seguimiento realizado por el profesional'
    NO_CONFORME = 'No estoy conforme con el seguimiento realizado por el profesional'
    CALIFICACION =[
        (SELECCIONAR, 'Seleccione una opción'),
        (NO_CONTACTADO, 'No fuí contactado nunca por el profesional encargado del seguimiento'),
        (NO_SEGUIDO, 'El profesional no realiza el seguimiento todos los días'),
        (CONFORME, 'Estoy conforme con el seguimiento realizado por el profesional'),
        (NO_CONFORME, 'No estoy conforme con el seguimiento realizado por el profesional')
    ]
    dni = models.CharField(max_length=12)
    numero_afiliado = models.CharField(max_length=20)
    nombre = models.CharField(max_length=120)
    calificacion = models.CharField(max_length=75, choices=CALIFICACION, default=SELECCIONAR)
    opinion = models.TextField()
    celular = models.CharField(max_length=25)
    email = models.CharField(max_length=120)
    
    def __str__(self):
        return '{} - {}'.format(self.nombre, self.dni)
    
    class Meta:
        verbose_name_plural = "Seguimiento COVID"

apps/seguimiento/forms.py
from django import forms

# Modelos
from .models import Seguimiento



class SeguimientoForm(forms.ModelForm):
    class Meta:
        model = Seguimiento
        fields = ['dni', 'numero_afiliado', 'nombre', 'calificacion', 'opinion', 'celular', 'email']
        labels = {
            'dni': "DNI",
            'numero_afiliado': "Número de Afiliado",
            'nombre': "Nombres y Apellido",
            'calificacion': "Calificación",
            'opinion': "Opinion",
            'celular': "Celular",
            'email': "Email",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

apps/seguimiento/views.py
from django.shortcuts import render

from django.urls import reverse_lazy

# Vistas genéricas
from django.views import generic

# Mensajes
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

# Mixins
from django.contrib.auth.mixins import LoginRequiredMixin

import django_excel as excel

from datetime import datetime

# Formularios
from .forms import SeguimientoForm

# Modelos
from .models import Seguimiento


# Publico
class SeguimientoNew(SuccessMessageMixin, generic.CreateView):
    model = Seguimiento
    template_name = 'public/seguimiento_form.html'
    context_object_name = 'obj'
    form_class = SeguimientoForm
    success_message = "Sus datos fueron registrados exitosamente"
    success_url = reverse_lazy("seguimiento:datos_recibidos")


class ReceivedData(generic.TemplateView):
    template_name = 'public/datos_recibidos.html'


# Restringido
class PatientList(LoginRequiredMixin, generic.ListView):
    model = Seguimiento
    template_name = 'dashboard/listado_pacientes.html'
    context_object_name = 'obj'
    login_url = 'usuarios:inicio'


def download_patient_list(self):
    # https://www.comoinstalarlinux.com/como-exportar-a-un-excel-con-python-y-django/
    export = []

    export.append(['DNI', 'N° de Afiliado', 'Nombre', 'Fecha de Carga', 'Calificación', 'Opinión', 'Celular', 'Email'])
    results = Seguimiento.objects.all()

    for result in results:
        export.append([
            result.dni,
            result.numero_afiliado,
            result.nombre,
            result.fecha_creacion,
            result.calificacion,
            result.opinion,
            result.celular,
            result.email,
        ])

    today = datetime.now()
    strToday = today.strftime("%d%m%Y")

    # se transforma el array a una hoja de calculo en memoria
    sheet = excel.pe.Sheet(export)

    # se devuelve como "Response" el archivo para que se pueda "guardar"
    # en el navegador, es decir como hacer un "Download"
    # return excel.make_response(sheet, "csv", file_name="results-" + strToday + ".csv")
    # return excel.make_response(sheet, "ods", file_name="results-" + strToday + ".ods")
    return excel.make_response(sheet, "xlsx", file_name="listado_pacientes_covid_osep-" + strToday + ".xlsx")

apps/seguimiento/templates/dashboard/listado_pacientes.html
{% extends "dashboard/base.html" %}

{% block contenido %}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3>Listar Pacienes con COVID-19</h3>
    </div>
    <br>
    <div class="text-center">
        <a href="{% url 'seguimiento:descargar_listado_pacientes' %}" class="btn btn-info">Descarga Listados</a>
    </div>

    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="tabla">
            <thead>
                <tr>
                    <th>DNI</th>
                    <th>N° Afiliado</th>
                    <th>Apellido y Nombre</th>
                    <th>Fecha de Carga</th>
                    <th>Calificación</th>
                    <th>Opinión</th>
                    <th>Celular</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.dni }}</td>
                    <td>{{ item.numero_afiliado }}</td>
                    <td>{{ item.nombre|upper }}</td>
                    <td>{{ item.fecha_creacion }}</td>
                    <td>{{ item.calificacion }}</td>
                    <td>{{ item.opinion }}</td>
                    <td>{{ item.celular }}</td>
                    <td>{{ item.email }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock contenido %}